DATABASE_DATABASE: 'krazownik_development'
DATABASE_HOST: 'localhost'
DATABASE_PASSWORD: 'szikaka'
DATABASE_POOL: '5'
DATABASE_PORT: ''
DATABASE_USERNAME: 'staszek'

CORS_ORIGINS: '*'
BACKEND_APP_URL: 'http://localhost:4321'
SMS_TOKEN: '27069a41d37d4baaa3390adeedabe573'
