default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: krazownik_api_development

test:
  <<: *default
  database: krazownik_api_test

production:
  <<: *default
  database: krazownik_api_production
  username: krazownik_api
  password: <%= ENV['KRAZOWNIK_API_DATABASE_PASSWORD'] %>
